### ISSUE TITLE
add a full breadcrumb trail across packages

### ISSUE THREAD

**Issue by avsm** [dbuenzli/odig#11]
via @mato in mirage/mirage#609

A "Path" navigation header with the full hierarchy. E.g. rresult/Result.html currently has "Up", which takes me to the package's index.page but I can't go "Up" from there to the main package list.

**Comment by dbuenzli** [comment]
I don't think I'll add a full breadcrumb, choice is not necessarily more efficient from an UI point of view. 

What I'd like is on each page:

1. A direct link to the list of packages
2. A direct link to the root of the current package
3. A consistent `Up` link located at the same place on the trail that brings you from the current page to the package list.

But for this I need https://github.com/ocaml-doc/odoc/issues/14

**Comment by dbuenzli** [comment]
Consistent up-link until you hit the package index has been implemented in both backends, though in the `ocamldoc` backend you may have to move your pointer because of https://caml.inria.fr/mantis/view.php?id=6928
