### ISSUE TITLE
ppx in mli seem to confuse odig

### ISSUE THREAD

**Issue by avsm** [dbuenzli/odig#12]
I was looking at some of the errors in http://docs.mirage.io and

```
$ odig ocamldoc pcap-format
Processing pcap-format.
File "/Users/avsm/.opam/system/lib/pcap-format/pcap.mli", line 57, characters 5-12:
Uninterpreted extension 'cstruct'.
1 error(s) encountered
$ odig ocamldoc pcap-format
Processing pcap-format
```

Subsequent runs seem not to error out.  The mli should be run through the ppx_cstruct before the cmti is generated, so where is this error coming from?

**Comment by dbuenzli** [comment]
Well I'm afraid I can't possibly have that info. Rather pcap-format should install proper mli files not franken-mli files. [AFAIK](https://github.com/ocaml/ocaml/pull/827#issuecomment-250160476) these problems should be solved by `cmti` files and hence `odoc`.

> Subsequent runs seem not to error out.

There's a cache that remembers there was an error to avoid repeatedly spitting out errors when you simply `odig ocamldoc` to bring the documentation of your switch up-to-date. Invoke with `odig ocamldoc --force` to see the error again.

**Comment by dbuenzli** [comment]
> The mli should be run through the ppx_cstruct before the cmti is generated, so where is this error coming from?

A sorry didn't understand the question correctly. `ocamldoc` is oblivious of `cmti` files it works on mli files.

**Comment by avsm** [comment]
Ah I see, so this should be documented as a limitation of the ocamldoc backend. Will do.
