### ISSUE TITLE
Specify target directory for CHANGES/LICENSES and copy them there

### ISSUE THREAD

**Issue by avsm** [dbuenzli/odig#13]
Right now CHANGES and LICENSES are specified by a relative path into `.opam`, e.g.: `<a href="../../../../../doc/channel/LICENSE.md`.  This doesnt work well when running an HTTP server like docs.mirage.io with a document root pointing at the ocamldoc output directly.

Would it be possible to have an odig option to copy the various LICENSE and CHANGES file into a target directory suitable for publishing without deep relative symlinks?

**Comment by dbuenzli** [comment]
I didn't want to copy, your server may be able to serve them where they are. 

So there is now an `docdir_href` configuration option which you can easily set on the cli via the `--docdir-href URI` option when you `odig [odoc|ocamldoc]`. It specifies the root URI at which the docdir can be found. If URI is relative it is expressed w.rt. to the root package index. 

I'll PR the mirage dockerfile to show you how it works.
