### ISSUE TITLE
authors/maintainers has © instead of @

### ISSUE THREAD

**Issue by edwintorok** [dbuenzli/odig#14]
Due to [this](https://github.com/dbuenzli/odig/blob/478b5fb328b7a942f7aa0089158b984b7cbcb177/src/odig_html.ml#L32):
```ocaml
 | '@' -> flush g.b start i; adds "&copy;" g; loop next next
```

Any reason it gets encoded as `&copy` instead of `&commat`, would ocamldoc [trip](https://github.com/dbuenzli/odig/blob/478b5fb328b7a942f7aa0089158b984b7cbcb177/src/odig_html.ml#L17) over `&commat` too?

**Comment by dbuenzli** [comment]
Uh no. This likely a bug...
