### ISSUE TITLE
Allow mining packages from several directories

### ISSUE THREAD

**Issue by regnat** [dbuenzli/odig#29]
`odig` allows choosing the directory from which to search for installed packages (via the `libdir` and `docdir` config options). However, it only allows choosing one directory, which makes the tool unusable if for some reasons several packages are installed in several different directories (which is something that is fully supported by the rest of the ecosystem like `ocamlfind` whose `path` configuration variable takes as argument a list of directories to search in instead of a single directory).

A concrete need for this is for users of the Nix package manager, in which every package is installed under its own prefix.

**Comment by dbuenzli** [comment]
What's the `Nix` layout exactly ?

**Comment by regnat** [comment]
The compiled files (and the META) for a package `foo` will be installed under `/nix/store/<some-hash>-foo/lib/ocaml/<ocaml-version>/site-lib/foo/` (and a package `bar` will be installed under `/nix/store/<another-hash>-bar/...`).

**Comment by dbuenzli** [comment]
So what is your proposal ? It seems impractical to have to specify directories for each of the package, also once you allows to specify more than one directory it's no longer possible to guarantee package name unicity via the file system.

**Comment by regnat** [comment]
My proposal is simply to specify more than one directory. We loose the guaranty of package name unicity, but it doesn't seem hard to check and fail if the same package exists at several locations − I assume there already is a check to guaranty module name unicity anyway.

**Comment by dbuenzli** [comment]
> My proposal is simply to specify more than one directory.

But this means we are going to `readdir` hundreds of dirs to lookup a package name. 

> I assume there already is a check to guaranty module name unicity anyway.

No, for different reasons module unicity is not a property you want in a package install.

**Comment by regnat** [comment]
> But this means we are going to |readdir| hundreds of dirs to lookup a
> package name.
>
In the worst case, it could be possible, yes, but (at least for the Nix
use-case), the architecture encourages you to have only the packages
that you need for the current project available, so most of the time not
that much − for example in an environment with all the dependencies of
`core` installed, the "OCAMLPATH" variable (which tells `ocamlfind`
where to find the packages) contains "only" 39 entries. I don't know of
any measure, but at least for ocamlfind, the lookup time is small enough
not to be noticeable.

**Comment by dbuenzli** [comment]
I will simply implement what @lpw25's scheme is going to be for namespaces which I guess should be able to operate in a `nix` world, I don't remember what the scheme was though.

**Comment by regnat** [comment]
Do you have any pointer about this scheme ? I only could find [this](http://www.lpw25.net/2013/03/10/ocaml-namespaces.html), but it's rather old so I'm not sure it is still accurate

**Comment by dbuenzli** [comment]
Unfortunately not it's tucked in @lpw25's brain.

**Comment by lpw25** [comment]
I'm writing an outline at the moment. Should manage to get something readable in the next couple of weeks.

**Comment by dbuenzli** [comment]
@regnat you can have a look at https://github.com/lpw25/namespaces

**Comment by dbuenzli** [comment]
@regnat I don't know much about nix but in that discussion @lpw25 mentions:

```
With regards of using odig with Nix, I think that Nix already provides the notion of "user
environment" that contains symlinks to all the things currently installed. I would expect odig 
to just use this as its input rather than taking the parts of the Nix store directly.
```
Did you investigate this ?

**Comment by dbuenzli** [comment]
@regnat without any further feedback from you (see last message) I'm going to close this.

**Comment by regnat** [comment]
@dbuenzli sorry, somehow missed your last messages.

Bundling all the dependencies like suggested by @lpw25 is a possibility indeed and is probably good-enough − that's already more or less how the haskell packaging works and it is a robust-enough solution for Nix to be widely used in the haskell community.

Anyway, this isn't top-priority for me anymore since I'm hardly writing OCaml anymore and probably won't be solved on odig side, so I'm closing this.
