### ISSUE TITLE
"odig doc" failing on MacOS 10.13.2 with Chrome

### ISSUE THREAD

**Issue by pmetzger** [dbuenzli/odig#33]
Running "odig doc sedlex" on MacOS 10.13.2 with my browser set to Chrome does this:

    $ odig doc sedlex
    1934:1971: execution error: Error on line 55: Error: Invalid index. (-1719)
    odig: [ERROR] run ['osascript' '-l' 'JavaScript' '-' 'false' 'false'
              'com.google.chrome'
                  
              'file:///Users/perry/.opam/4.06.0/var/cache/odig/odoc/sedlex/index.html']:
              exited with 1
              browser reload: run ['osascript' '-l' 'JavaScript' '-' 'false'
              'false' 'com.google.chrome'
                  
              'file:///Users/perry/.opam/4.06.0/var/cache/odig/odoc/sedlex/index.html']:
              exited with 1

**Comment by dbuenzli** [comment]
This seems to be a problem with [`webbrowser`](https://github.com/dbuenzli/webbrowser) can you please reproduce the problem with the `browse` cli tool  and report the error there.

**Comment by pmetzger** [comment]
I can try to do that. Can you suggest what I should run? I will then go to that package and report the problem...

**Comment by pmetzger** [comment]
Never mind, I think I got a reproducing case pretty easily.

**Comment by dbuenzli** [comment]
Thanks, I could indeed have been more specific. The issue was https://github.com/dbuenzli/webbrowser/issues/4
