### ISSUE TITLE
Discussion: do not generate {%...%} (ocamldoc target-specific code)

### ISSUE THREAD

**Issue by aantron** [dbuenzli/odig#35]
`odig odoc` currently generates `{%...%}` markup in order to insert custom HTML into odoc output:

https://github.com/dbuenzli/odig/blob/e8a4d7cd6ff9fa35410cd8589a0bbe977a17b964/src/odig_api_doc.ml#L299-L307

This issue is to discuss how to avoid doing this, or whether it should be avoided.

odoc's new parser currently forbids arbitrary HTML. The idea is that we don't want to consider security risks for a centralized deployment, at least not now.

In practice, `{%...%}` is almost never used in OCaml documentation. There was about one occurrence of it in 1400 packages in a test run of the new odoc parser. So, it seems like a good opportunity to drop support for `{%...%}`.

So, I suggest patching odig to avoid `{%...%}`. Please let me know if something else is needed from odoc to support odig here. Alternatively, if the assumptions in this issue are faulty, discussion is welcome.

For comparison, we removed `{%...%}` from Jbuilder's output a few months ago: https://github.com/ocaml/dune/pull/367/commits/0aa6faa14529278bf864ab078638dae8826592a4

**Comment by dbuenzli** [comment]
First, in general, for packages `%html:` is currently the only way we have to embed media (in particular images) in documentation. See for example [Vg's doc](http://erratique.ch/software/vg/doc/Vg.html#scissors) ([src](https://github.com/dbuenzli/vg/blob/da3b840da6c9d1f0ed22413dfcb7a6c7e4cdb27d/src/vg.mli#L992-L993) or `opam install vg && odig odoc vg && odig doc`) and https://github.com/ocaml/odoc/issues/59 and https://github.com/dbuenzli/odig/issues/6 and [here](https://github.com/dbuenzli/odig/blob/e8a4d7cd6ff9fa35410cd8589a0bbe977a17b964/src-bin/help.ml#L125-L127) for discussion. I'll gladly replace the current hacks by a good solution for this.

Second for `odig` the code is not specific to `ocamldoc`, it is used to generate the package metadata (see e.g. [here](http://docs.mirage.io/alcotest/index.html)), do the per archive module sorting and archive name insertion,  and add direct links to important elements next to the package name.  I'm not sure I can really get rid of it but I'll see that when I iterate on odig in the upcoming weeks. 

> odoc's new parser currently forbids arbitrary HTML. The idea is that we don't want to consider security risks for a centralized deployment, at least not now.

I'm rather unconvinced about the security argument any link nowadays is basically a security risk. There was a discussion once (can't find it) with someone making the case that `%html:` was a security risk. But from an end-user perspective the point is a little bit moot when you already allowed someone to run arbitrary programs at package install on your machine. 

If you really worry about this I think you should rather implement a `--drop-html` option in `odoc`. However I still think that he `%html` escape hatch is useful in general. FWIW lightweight markup language like [markdown](http://spec.commonmark.org/0.28/#html-blocks) and [doxygen](http://doxygen.nl/commands.html#cmdhtmlonly) also provide these.

/cc @lpw25 @trefis

**Comment by trefis** [comment]
> If you really worry about this I think you should rather implement a --drop-html option in odoc.

That seems reasonable to me.

**Comment by aantron** [comment]
That seems reasonable to me as well.

I agree and think we should eventually have odoc support images and such, without requiring `{%...%}`.

I'm not certain about whether arbitrary code running during package build/install can result in arbitrary markup being generated by odoc. That probably depends on the order in which Dune executes rules, as well as how vulnerable `compiler-libs` is (I guess it's *very* vulnerable in this scenario).

It's probably not worth addressing the above now, for a non-existent security risk. However, in case we have to deal with it in the future, it seems like it would be good if using `{%...%}` had not by then become a common practice. So, I think we should allow `{%...%}`, but discourage it, perhaps with a warning, and provide alternative mechanisms, as discussed above.

**Comment by dbuenzli** [comment]
> I'm not certain about whether arbitrary code running during package build/install can result in arbitrary markup being generated by odoc.

That's not really the point. The point is that you need to be able to trust packagers up to a certain level and that's what we all do when we use `opam`. So if you trust them on not doing any fancy on your machine when you install their packages and allow them to run arbitrary scripts on your machine, you should also be able to trust them in not doing anything in their doc gen. 

That said why don't you simply sanitize the input and drop dangerous tags/attributes ? I'm not well versed in the subject but looking up for `html sanitization` it seems there are dozens of (non-ocaml) libraries that provide that kind of service.

> So, I think we should allow {%...%}, but discourage it, perhaps with a warning,

Please don't do warnings if there's no way to fix them (which is the case now). They just became false positives and an annoyance for users.

**Comment by rizo** [comment]
Just for a reference, what would you consider to be a set of "dangerous tags/attributes"? For example, the wikipedia page on [HTML sanitization](https://en.wikipedia.org/wiki/HTML_sanitization) mentions `<scrript>` which is valid, but how would one embed interactive examples/diagrams otherwise?

I think `{%...%}` can only be removed if alternative ways to achieve a subset of useful features is provided. Adding the ability to inject header/footer templates is an example.

**Comment by dbuenzli** [comment]
I think this discussion is over, so I'm closing this. Feel free however to continue it if you see it fit.
