### ISSUE TITLE
Support for ressources linked from the API docs

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/odig#6]
`odig` should introduce a convention so that docs can include e.g. images (one package that needs this is `vg`). 

This could be simply that whatever is in `$(opam var PKG:doc)/odoc-assets` is simply copied over to an `assets` directory in the package's html directory. API doc strings could then simply refer to these using relative links (e.g. for Vg)

```
 {%html: <img src="assets/doc-earcs.png" style="width:75mm; height:45mm;"/> %}
```

One slight annoyance is that two copies of the assets would live in the switch.

**Comment by dbuenzli** [comment]
> API doc strings could then simply refer to these using relative links (e.g. for Vg)

In fact this will be annoying with `odoc` which doesn't have a flat generation structure. 

In fact it would be nice to have a symbolic variable for the root of assets that can be used in API docstrings. This would also allow to prevent the copy of assets as we could generate the docs with the assets root set to `$(opam var PKG:doc)/odoc-assets`. 

@lpw25 @trefis thoughts ?

**Comment by lpw25** [comment]
This seems reasonable, although I wonder whether some more direct support for including images would be easier to use. You could imagine a reference to an image "foo/bar" in an odoc file, and then having a command like `odoc image --package foo --name bar foobar.png`.

**Comment by dbuenzli** [comment]
Note sure that would be *easier* to use... but the advantage is that you could check for missing ressources rather than having to wait for people to get 404 to realise something is missing --- that is assuming I can ask for the actual ressource ids an `.odoc` needs through an `odoc` command. 

The problem is that some form of support would be needed in the doc string language. So as a first measure I may simply implement the above (the problem however being that this cannot be made to work for both the `ocamldoc` and  `odoc` backend).

**Comment by dbuenzli** [comment]
(This should not be only for images btw. sound, videos, what not).

**Comment by lpw25** [comment]
Ok that sounds like a plan

**Comment by dbuenzli** [comment]
Something has been done in 90f8660 and documented in `odig help packaging` which is good enough for e.g. `Vg`'s image (https://github.com/dbuenzli/vg/commit/e01ae8eb6214725c8aae0a3fd5a001787fc89782). 

As I said in https://github.com/ocaml-doc/odoc/issues/59 I don't think `odig` is the right place to solve the problem and that a scheme should be found in `odoc` and discussed there.
