### ISSUE TITLE
Wrong exit status code with `odoc` ?

### ISSUE THREAD

**Issue by tatchi** [dbuenzli/odig#64]
In a project where `ocaml-lsp-server` is installed, using the `doc` command to show the documentation for that package produces an error:

```bash
bash-3.2$ odig doc ocaml-lsp-server
Updating documentation, this may take some time...
odig: [ERROR] No doc could be generated for:
              '/Users/corentin/Dev/temp/routes/_opam/var/cache/odig/html/ocaml-lsp-server/index.html'
bash-3.2$ echo $?
3
```

While the `odoc` command doesn't produce any error (exit code is 0), although nothing has been generated in the `_opam/var/cache/odig/odoc` folder.

```bash
bash-3.2$ odig odoc ocaml-lsp-server
Updating documentation, this may take some time...
bash-3.2$ echo $?
0
```

Is it the expected behaviour? I would have expected an error exit code.

**Comment by dbuenzli** [comment]
> Is it the expected behaviour?

It may be. 

In the first invocation apparently I can't open the said the file to show it to the user so I can't satisfy the request. 

In the second invocation there may simply be nothing to generate which may not be an error or the error is masked – in general `odig odoc` will not error even if there are erroring invocation of `odoc` as there will always be some in a switch so it makes the erroring exit code more annoying than useful. 

What does `odig log -e` or `odig log` say after the invocation in the second case ?

**Comment by tatchi** [comment]
Thanks for the detailed explanation. I should probably have explained what I'm trying to achieve, sorry for that.

I'm trying to implement a new feature for the OCaml VSCode extension. The idea is that users would be able to see the documentation for installed packages inside VSCode. The way it works is:

 1. Display the list of installed packages somewhere in the VSCode UI (`opam list --roots`)
 2. Let the user choose one of them for which he would like to see the doc
 3. Generate the documentation for that package `odig odoc`
 4. Display the package's HTML content in a new VSCode tab.
 
 You can find an example in the video below:

https://user-images.githubusercontent.com/5595092/138143641-306c6941-d843-445e-afe3-8f93106c1696.mov


I noticed at some point that generating the doc for `ocaml-lsp-server` didn't work (for the reason you mentioned above). I wanted to handle that case (display a message or whatever) but noticed that the `odoc` command" succeed (exit code = 0). 

I just thought that it was probably a bug since the `odig doc` command, in that case, produces an error code. Thanks to your explanation, I understand now that it's not an error for a package to have no documentation or to fail at generating its documentation. 

That's definitely not an issue in my case anyway, I can myself do some checks before I try to open the documentation inside VSCode (like `odig doc` does). 

Thanks again for your time and your help, it's definitely clearer for me now 🤗
