### ISSUE TITLE
Support for customising front page of ocamldoc

### ISSUE THREAD

**Issue by avsm** [dbuenzli/odig#7]
We have started to generate documentation for MirageOS 3, available at http://docs.mirage.io using odig.

The front page of the generated documentation is rather busy, and it would be useful to be able to break it out into a few sections based on the tag of the libraries.  I imagine something with the core libraries in one section, followed by various protocol-specific ones (web, network, tls) under separate sections.

Happy to write OCaml code to accomplish this rather than templating.

**Comment by dbuenzli** [comment]
One issue I have with this is that the effort you put in this presentation won't be available to local users of `odig`. 

One way to side-step this would be to write this presentation in one of the main toplevel modules of mirage and link to tags on the current page index page (whose presentation I may change a bit in the future) or even in a special `mirage-docs` package.

This could also be solved by allowing to add paragraphs to the package landing page via a mecanism similar to #6. This chunking presentation could then be added to the `mirage` package page linking on the appropriate tags. But we need to see what `odoc` wants to do on that front (https://github.com/ocaml-doc/odoc/issues/12).

**Comment by dbuenzli** [comment]
(also note that in the future the alphabetic list will not show up raw package names as they do now but complemented by the OPAMv2 `synopsis:` field which may help a bit more figuring out what the packages are about).

**Comment by dbuenzli** [comment]
Another example would be landing page of BAP https://binaryanalysisplatform.github.io/bap/api/v1.0.0/argot_index.html

This landing page links across packages (besides it also links on html rendering of manpages, which could be supported via #6). However we beyond this page we are then immediately in regular module docs.

Here again a customization of `bap`'s package page could do I guess.

**Comment by dbuenzli** [comment]
Won't work immediately on that but just looping in @ivg if he has comments or ideas.

**Comment by avsm** [comment]
> One way to side-step this would be to write this presentation in one of the main toplevel modules of mirage and link to tags on the current page index page (whose presentation I may change a bit in the future) or even in a special mirage-docs package.

Yes this seems like a good solution, since it'll be available to non-HTML outputs as well then.

**Comment by dbuenzli** [comment]
Closing this in favour of #18 and #19.
